# Site settings
title: Michael Hinterdorfer
description: My Personal Homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://michael-hinterdorfer.me/"

# User settings
username: mhinterdorfer
user_description: Software Developer
user_title: Michael Hinterdorfer
email: michael.hinterdorfer@outlook.at
twitter_username: m_hinterdorfer
github_username:  mhinterdorfer
linkedin_username: mhinterdorfer

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# links
links:
  - title: Home
    url: /
  - title: Résumé
    url: /resume.html#content
  - title: Blog
    url: /blog.html
    
# collections
collections:
    cards:

exclude: ['package.json', 'src', 'node_modules', 'vendor']
