# Site settings
title: Michael Hinterdorfer
description: My Personal Homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mhinterdorfer.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: mhinterdorfer
user_description: Software Developer
user_title: Michael Hinterdorfer
email: michael.hinterdorfer@outlook.at
twitter_username: m_hinterdorfer
github_username:  mhinterdorfer

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', 'vendor']
